version: 2
jobs:
    install-job:
        docker:
            - image: circleci/node:dubnium
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - node-modules-{{ checksum "yarn.lock" }}-v6

            - run: yarn install --frozen-lockfile

            - save_cache:
                  key: node-modules-{{ checksum "yarn.lock" }}-v6
                  paths:
                      - node_modules
                      - ~/.cache
            - persist_to_workspace:
                  root: ~/
                  paths:
                      - repo/node_modules/*
                      - .cache/*

    test-job:
        docker:
            - image: circleci/node:dubnium

        working_directory: ~/repo

        steps:
            - checkout
            - attach_workspace:
                  at: ~/
            - run: yarn test

    lint-job:
        docker:
            - image: circleci/node:dubnium

        working_directory: ~/repo

        steps:
            - checkout
            - attach_workspace:
                  at: ~/
            - run: yarn lint

    build-job:
        docker:
            - image: circleci/node:dubnium

        working_directory: ~/repo

        steps:
            - checkout
            - attach_workspace:
                  at: ~/
            - run: yarn build

    coverage-job:
        docker:
            - image: circleci/node:dubnium

        working_directory: ~/repo

        steps:
            - checkout
            - attach_workspace:
                  at: ~/
            - run: yarn test:coverage
            - run: yarn coveralls

    cypress-job:
        docker:
            - image: circleci/node:dubnium-browsers

        working_directory: ~/repo

        steps:
            - checkout
            - attach_workspace:
                  at: ~/
            - run: yarn cypress run

workflows:
    version: 2
    build-deploy:
        jobs:
            - install-job
            - build-job:
                  requires:
                      - install-job
            - test-job:
                  requires:
                      - install-job
            - lint-job:
                  requires:
                      - install-job
            - coverage-job:
                  requires:
                      - install-job
            - cypress-job:
                  requires:
                      - install-job
